image: node:18

pipelines:
  branches:
    master:
      - step:
          name: production
          caches:
            - node
          script:
            - export NODE_OPTIONS=--max_old_space_size=4096
            - npm install
            - npm install serverless -g
            - serverless config credentials --stage prod --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - sls deploy --stage prod
    dev:
      - step:
          name: development
          caches:
            - node
          script:
            - export NODE_OPTIONS=--max_old_space_size=4096
            - npm install
            - npm install serverless -g
            - serverless config credentials --stage dev --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - sls deploy --stage dev
